version: '3.3'
services:
  mysql-test:
    image: "mysql:latest"
    ports:
      - "3309:3306"
    command: "--default-authentication-plugin=mysql_native_password --init-file /data/application/create_table.sql"
    environment: 
      MYSQL_ROOT_PASSWORD: "root123456"
      MYSQL_DATABASE: "app"
      MYSQL_PASSWORD: "root123456"
    volumes:
      - ./models/create_table.sql:/data/application/create_table.sql
  app-test:
    build: .
    command: sh -c "./wait-for.sh mysql-test:3306 -- ./app-test config.yaml"
    depends_on:
      - mysql-test
    ports:
      - "8088:8080"